// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljhlkxoyyuvdckoamwfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqaGxreG95eXV2ZGNrb2Ftd2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODcxMDcsImV4cCI6MjA3MjQ2MzEwN30.QJiw0uALLQoIgMYMuKtTDxJy00aeZf6JtR8PdSh8XTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});